<?php
/**
 * Pmclain_AuthorizenetCim extension
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GPL v3 License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://www.gnu.org/licenses/gpl.txt
 *
 * @category  Pmclain
 * @package   Pmclain_AuthorizenetCim
 * @copyright Copyright (c) 2017
 * @license   https://www.gnu.org/licenses/gpl.txt GPL v3 License
 */

/** @var Pmclain\AuthorizenetCim\Block\Payment $block */
$code = $block->escapeHtml($block->getCode());
?>

<script>
  //<![CDATA[
  require(
    [
      'Pmclain_AuthorizenetCim/js/acceptjs',
      'jquery',
      'domReady!'
    ], function(PmAcceptJs, $) {
      var config = <?php /* @noEscape */ echo $block->getPaymentConfig(); ?>;
      var payment;
      var form = $('#payment_form_<?php /* @noEscape */ echo $code; ?>');

      config.active = form.length > 0 && !form.is(':hidden');
      payment = new PmAcceptJs(config);
    });
  //]]>
</script>