<?php
/**
 * Pmclain_AuthorizenetCim extension
 * NOTICE OF LICENSE
 *
 * This source file is subject to the OSL 3.0 License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * @category  Pmclain
 * @package   Pmclain_AuthorizenetCim
 * @copyright Copyright (c) 2017-2018
 * @license   Open Software License (OSL 3.0)
 */

/** @var Magento\Vault\Block\Form $block */
$code = $block->escapeHtml($block->getMethodCode());
?>
<fieldset class="fieldset payment items ccard <?php /* @noEscape */ echo $code; ?>"
          id="payment_form_<?php /* @noEscape */ echo $code; ?>" style="display: none;">
    <input type="hidden" name="payment[public_hash]" id="<?php /* @noEscape */ echo $code; ?>_public_hash" value="" />
    <?php echo $block->getBlockHtml('pmclain_authorizenetcim_vault_tokens'); ?>
</fieldset>
